name: Waka Readme

on:
  # push:
  #   branches: [ master ]
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_BY_ME: "True"
          COMMIT_MESSAGE: "📊 Waka Stat's Updated❗"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROJECTS: "True"
          SHOW_LOC_CHART: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_UPDATED_DATE: "True"